version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app/
    environment:
      - OTEL_TRACE_HOST=tempo
      - LOKI_HOST=loki
      - JOB_NAME=observability
    depends_on:
      - loki
      - tempo
    healthcheck:
      test: [
          "CMD",
          "curl",
          "-f",
          "http://localhost:5000/health-check"
        ]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - loki
      - tempo
  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
    command: -config.file=/etc/loki/loki-config.yml
  tempo:
    image: grafana/tempo
    container_name: tempo
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
    command: [ "-config.file=/etc/tempo.yml" ]
    ports:
      - 14268:14268
      - 3200:3200
